---
title: "An Analysis of Lake Michigan-Huron Water Levels, ????-2021"
subtitle: "STATS531 Midterm Project, W21"
author: "Eric Chen (ericch), Yanyu Long (longyyu)"
date: "Feb 25, 2021"
output: 
  html_document:
    toc: true
    toc_depth: 2
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	message = FALSE,
	include = TRUE,
	comment='',
	fig.align = "center"
)
```


```{css, include = TRUE, echo = FALSE}
body{ /* Normal */
  font-size: 15px;
}
span.math{ /* Formulas */
  font-size: 14px;
}
pre { /* Scrollable code block */
  max-height: 250px;
  overflow-y: auto;
}
.comment { /* Comments, to be deleted later */
  margin: 30px;
  padding-left: 10px;
  color: Darkred;
  border-left-style: solid;
  border-color: #f2f2f2;
}
```


```{r, echo = FALSE}
opar = par()
library(tidyverse)

generate_aic_table=function(data, P, Q, D=0, ...){
	table=matrix(NA, (P+1), (Q+1))
	for(p in 0:P) {
		for(q in 0:Q) {
		  table[p + 1,q + 1] = arima(data, order = c(p, D, q), ...)$aic
		}
	}
	dimnames(table) = list(paste("AR", 0:P, sep=""), paste("MA", 0:Q, sep=""))
  table
}

format_aic_tables = function(table, ...) {
  min_idx = which(table == min(table), arr.ind = TRUE)
  table %>% 
    knitr::kable(
      format = "html", digits = 2, escape = TRUE, ...
    ) %>%
    kableExtra::row_spec(row = 0, align = 'c') %>%
    kableExtra::column_spec(column = 1, bold = TRUE) %>%
    kableExtra::kable_styling("striped", full_width = FALSE) %>%
    kableExtra::add_footnote(sprintf(
      "Model with the lowest AIC: %s %s, AIC = %4.2f\n",
      rownames(table)[min_idx[1, 1]], colnames(table)[min_idx[1, 2]],
      min(table)
    ))
}

generate_acf_qqplot = function(model) {
  par(mfrow = c(1, 2))
  acf(model$resid, na.action = na.pass, 
      main = "Autocorrelation function estimation")
  qqnorm(as.numeric(model$resid))
  qqline(as.numeric(model$resid))
  par(opar)
}
```


------------

## Introduction.

The Great Lakes are a major source of water, recreation, and industry for over 30 million people. However, in recent years, residents have been concerned about steadily rising lake levels, as evidenced by these news articles from the [Green Bay Gazette](https://www.greenbaypressgazette.com/story/news/local/oconto-county/2020/08/04/lake-michigan-breaks-34-year-old-high-water-record/3294377001/), [Detroit Free Press](https://www.freep.com/story/news/local/michigan/2020/07/17/great-lakes-water-levels-records-erosion-damage/5450910002/), [Washington Post](https://www.washingtonpost.com/weather/2019/11/08/great-lakes-water-levels-have-swung-record-lows-record-highs-heres-why/), and more. Rising lake levels can result in property damage, shoreline erosion, and economic disruption. Tying into the larger conversation about climate change, environmental scientists have been investigating the potential causes and implications of high water in the Great Lakes.

In this project, we consider the variation in water levels in Lake Michigan-Huron over the time period $????$-2021. We hope to identify some trends in ?

The data consists of monthly lake level means and was downloaded from the Great Lakes Environmental Research Laboratory (GLERL), an arm of the National Oceanic and Atmospheric Administration (NOAA).

- 

N.B.: Lake Michigan and Lake Huron are hydrologically [one lake](https://en.wikipedia.org/wiki/Lake_Michigan%E2%80%93Huron), since the flow of water through the Straits of Mackinac keeps their respective water levels in near-equilibrium. 

------------

## Data

[Data cleaning, exploratory analysis, spectrum analysis ... ]{.comment}


The wheat price data come from the USDA Agricultural Marketing Service. Specifically, we are analyzing the cash prices (dollars per bushel) of No. 2 soft red winter wheat, Chicago. 


```{r echo=FALSE}
## reading in and formatting data

months = c(1:12)
names(months) = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

data = read.csv('michigan_huron_level.csv')
date_labels = substr(data$Date, 1, nchar(data$Date) - 3)
data$Date = as.Date(data$Date)
```


```{r, fig.width=7, fig.height=4}
data %>%
  ggplot(aes(Date, MSL..ft.)) + 
      theme_bw() +
      geom_line(color="#69b3a2") +
      # scale_color_brewer(palette = "Set3") +
      ggtitle('Lake Michigan-Huron Water Levels, ????-2021') +
      ylab("Mean Lake Level (ft)") +
      theme(axis.text.x=element_text(angle=60, hjust=1), plot.title=
            element_text(hjust=0.5)) 
```

```{r, fig.width = 6, fig.height = 5}
plot(ts.union(ts_price, ts_import))
```

### Spectrum analysis  

```{r, fig.width = 6, fig.height = 5}
stl(ts_price, s.window = "periodic") %>% plot
```

```{r, fig.width = 6, fig.height = 5}
# transform Date to numeric type
date_num = seq(from = 1970 + 5/12, length = nrow(wheat_price), by = 1/12)

price = data$
p_low = ts(loess(price ~ date_num, span = 0.5)$fitted, 
           start = c(1970, 6), frequency = 12)
p_high = ts(price - loess(price ~ date_num, span = 0.1)$fitted, 
            start = c(1970, 6), frequency = 12)
p_cycles = price - p_low - p_high
plot(ts.union(price, p_low, p_high, p_cycles),
     main = "Decomposition of wheat prices as trend + noise + cycles")
```



------------

## Methods  

[Equations, hypotheses, notations, ...]{.comment}

------------

## Results  

[Model selection, residual analysis, causality, invertibility, ...]{.comment}

```{r, fig.width = 6, fig.height = 3}
attach(wheat_allvar)

## Model 1: ARMA
generate_aic_table(Price, P=5, Q=5, D=0) %>% 
  format_aic_tables(caption = "AIC of $ARMA(p, q)$ models, $0 \\leq p, q \\leq 5$")
m1 = arima(Price, c(5, 0, 4))
generate_acf_qqplot(m1)
params = coef(m1)
roots = list(
  ar = polyroot(c(1, -params[grep("^ar", names(params))])),
  ma = polyroot(c(1, params[grep("^ma", names(params))]))
)
lapply(roots, abs)


## Model 2: ARIMA
generate_aic_table(Price, P=5, Q=5, D=1) %>% 
  format_aic_tables(caption = "AIC of $ARIMA(p, 1, q)$ models, $0 \\leq p, q \\leq 5$")
m2 = arima(Price, c(5, 1, 4))
generate_acf_qqplot(m2)
params = coef(m2)
roots = list(
  ar = polyroot(c(1, -params[grep("^ar", names(params))])),
  ma = polyroot(c(1, params[grep("^ma", names(params))]))
)
lapply(roots, abs)
```

[Similarly, we can fit SARMA models and regression models with ARMA errors ...]{.comment}

```{r, fig.width = 6, fig.height = 3}
## Model 3: SARMA
# generate_aic_table(
#   Price, P=5, Q=5, D=0,
#   seasonal = list(order = c(1, 0, 0), period = 12)
# ) %>%
#   format_aic_tables(caption = "AIC of $SARMA(p, q) \\times (1, 0)_{12}$ models, $0 \\leq p, q \\leq 5$")
m3 = arima(Price, c(5, 0, 5), seasonal = list(order = c(1, 0, 0), period = 12))
generate_acf_qqplot(m3)


## Model 4: Regression with ARMA errors
generate_aic_table(Price, P=5, Q=5, D=0, xreg = Import) %>% 
  format_aic_tables(caption = "AIC of Regression with $ARMA(p, q)$ errors, $0 \\leq p, q \\leq 5$")
m4 = arima(Price, c(5, 0, 5), xreg = Import)
generate_acf_qqplot(m4)


detach(wheat_allvar)
```


```{r, fig.width=6, fig.height=3}
## plotting out fitted values
plot(wheat_allvar$Price, type = "l")
lines(wheat_allvar$Price - m1$resid, lty = 2, col = "red")
lines(wheat_allvar$Price - m2$resid, lty = 2, col = "green")
```


------------

## Conclusions  


------------

## References  

https://www.epa.gov/greatlakes/facts-and-figures-about-great-lakes 

https://en.wikipedia.org/wiki/Lake_Michigan%E2%80%93Huron


